import React from 'react'
import Head from 'next/head'

const Layout = ({ children, title = 'next-app' }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {children}
            </main>
        </div>
    )
}

export default Layout