import React from 'react'
import Head from 'next/head'
import NavBar from './NavBar'
import CartDrawer from './CartDrawer'

const Layout = ({ children, title = 'I will have order' }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar />
                <CartDrawer />
                {children}
            </main>
        </div>
    )
}

export default Layout